toptal/chewy

- README.md
> Update docs regarding new_relic

- lib/tasks/chewy.rake
Use the power of [Float#round](http://ruby-doc.org/core-1.9.3/Float.html#method-i-round).
```
1.9.3-p551 :013 > pi = 3.141592653589793
=> 3.141592653589793
1.9.3-p551 :014 > (pi * 100).round / 100.0
=> 3.14
1.9.3-p551 :015 > pi.round(2)
=> 3.14
```
> Simplify `subscribe_task_stats!`

- lib/chewy/query/criteria.rb
- spec/chewy/query/criteria_spec.rb
The feature can be useful to get a value on the search result which is calculated via scripts. It may be calculation distance between geopoints, for example.
> Allow to use scripting in the search criteria

- lib/chewy/query.rb
- spec/chewy/query_spec.rb
> Add search_type support

- lib/chewy/rspec/update_index.rb
This adds support for Mocha mocking library
> Check if mocha used for mocking library

- README.md
https://github.com/toptal/chewy/issues/179
> Add into README info about Chewy.use_after_commit_callbacks

- README.md
A fairly thorough language edit of the Readme.
> Readme proof edit

- lib/chewy/query.rb
Replace 'Deletes' with 'Find' in the .find method's comment block.
> Correct obvious mistake in comments of query

- lib/tasks/chewy.rake
- lib/tasks/rake_helper.rb
This PR moves existing rake helper method logic into an isolated module / file.
> Encapsulate rake helper methods

- lib/chewy/type/observe.rb
- lib/sequel/plugins/chewy_observe.rb
- spec/chewy/type/observe_spec.rb
Options `:if` and `:unless` are just passed to underlying callback definitions in mongo/active_record/sequel.
> Add condition options to `update_index` macro

- .travis.yml
- CHANGELOG.md
- Gemfile
- lib/chewy/config.rb
- lib/chewy/index.rb
- lib/chewy/index/settings.rb
- lib/chewy/query.rb
- lib/chewy/rspec/update_index.rb
- lib/chewy/strategy/atomic.rb
- lib/chewy/type.rb
- lib/chewy/type/adapter/active_record.rb
- lib/chewy/type/adapter/mongoid.rb
- lib/chewy/type/adapter/orm.rb
- lib/chewy/type/mapping.rb
> Documentation fixes

- README.md
> Logger.new needs an argument

- .travis.yml
- spec/chewy/runtime_spec.rb
- spec/chewy/type/import_spec.rb
Few tests were failing for me on current master since I'm using 1.7.2 on my OS X. I understand this may not be the case for other users / developers, so please close or merge this at will.
> Bump elasticsearch version

- README.md
- lib/chewy/query.rb
- lib/chewy/type/mapping.rb
- spec/chewy/query_spec.rb
- spec/chewy/type/mapping_spec.rb
Adds support for named aggregations as well as fully qualified named aggregations.
> Named aggs

- lib/chewy/type/import.rb
http://ruby-doc.org/core-2.3.0/Enumerable.html#method-i-flat_map
> Simplify Chewy::Type::Import#bulk_body a little

- lib/chewy/type/import.rb
> Fix a typo in exception messages

- spec/chewy/type/adapter/active_record_spec.rb
- spec/chewy/type/adapter/mongoid_spec.rb
- spec/chewy/type/adapter/sequel_spec.rb
> Fix a typo in spec descriptions

- lib/chewy/fields/base.rb
- lib/chewy/fields/root.rb
- lib/chewy/type/import.rb
- spec/chewy/fields/base_spec.rb
It should improve the performance slightly, especially for complex fields.
> Call as_json only on root field

- README.md
I did this one by hand. Would make sense to automate. But presented for you consideration like this.
> Docs: Create a Table of Content

- lib/chewy/type/adapter/sequel.rb
> complement primary_key to consider table name for correct behaviour for class table inherited requests

- lib/chewy/query/criteria.rb
- spec/chewy/query_spec.rb
https://github.com/toptal/chewy/issues/356
> Fix regression where order(nil) would be passed through as invalid sort

- README.md
- chewy.gemspec
- lib/chewy.rb
- lib/chewy/index.rb
- lib/chewy/index/actions.rb
- lib/chewy/journal.rb
- lib/chewy/rake_helper.rb
- lib/chewy/type.rb
- lib/chewy/type/import.rb
- lib/tasks/chewy.rake
- spec/chewy/index/actions_spec.rb
- spec/chewy/index_spec.rb
- spec/chewy/journal_spec.rb
- spec/spec_helper.rb
> Add journaling

- lib/chewy/journal.rb
- spec/chewy/journal_spec.rb
for [this](https://github.com/toptal/chewy/issues/422)
> Remove delete by query plugin dependency from Chewy::Journal

- CHANGELOG.md
- lib/chewy.rb
- lib/chewy/index.rb
- lib/chewy/index/actions.rb
- lib/chewy/index/aliases.rb
- lib/chewy/index/specification.rb
- lib/chewy/journal.rb
- lib/chewy/journal/query.rb
- lib/chewy/query.rb
- lib/chewy/rake_helper.rb
- lib/chewy/search/request.rb
- lib/chewy/type.rb
- lib/chewy/type/import/bulk_request.rb
- lib/chewy/type/syncer.rb
- spec/chewy/index/actions_spec.rb
- spec/chewy/index_spec.rb
- spec/chewy/journal/entry_spec.rb
- spec/chewy/type_spec.rb
- spec/chewy_spec.rb
Addresses https://github.com/toptal/chewy/pull/318 and https://github.com/toptal/chewy/pull/382
> Dynamic names

- lib/chewy/index/settings.rb
- spec/chewy/index/settings_spec.rb
Resolves https://github.com/toptal/chewy/issues/544
> Fix settings to support additional keys

- lib/chewy/fields/base.rb
- lib/chewy/fields/root.rb
- spec/chewy/fields/root_spec.rb
> Fix root field to accept value proc

- lib/chewy/fields/base.rb
- lib/chewy/fields/root.rb
- lib/chewy/type/witchcraft.rb
- spec/chewy/fields/base_spec.rb
- spec/chewy/fields/root_spec.rb
- spec/chewy/type/witchcraft_spec.rb
> Handle symbol or string field values correctly

- lib/chewy/railtie.rb
> Better initial strategies logging

- lib/chewy/rake_helper.rb
- spec/chewy/rake_helper_spec.rb
Fixed minor grammar mistake in one message.
> Improve wording

- lib/chewy/search.rb
- spec/chewy/index_spec.rb
- spec/chewy/search_spec.rb
> Cover scopes definitions with more specs

- .travis.yml
This PR updates the CI matrix.
> Travis: ruby 2.2.8, 2.3.5, 2.4.2

- README.md
Might be a bit pedantic, but the "it" is very ambiguous. Close #587
> Clarify switch to old DSL

- spec/chewy/index_spec.rb
> Specs for index inside index call

- lib/chewy/railtie.rb
> Use logger conditionally wherever possible

- README.md
Fixes newrelic_rpm status monitoring changes introduces in newrelic_rpm 4.x when upgrading from 3.x
related issue: #599 
all credit goes to barthez
> Update Readme to fix broken newrelic integration

- lib/chewy/index/specification.rb
- lib/chewy/stash.rb
- spec/chewy/index/specification_spec.rb
> Specification stored as json

- Appraisals
- Gemfile
- gemfiles/rails.4.0.activerecord.gemfile
- gemfiles/rails.4.1.activerecord.gemfile
- gemfiles/rails.4.2.activerecord.gemfile
- gemfiles/rails.4.2.mongoid.5.1.gemfile
- gemfiles/rails.5.0.activerecord.gemfile
- gemfiles/rails.5.0.mongoid.6.0.gemfile
- gemfiles/rails.5.1.activerecord.gemfile
- gemfiles/rails.5.1.mongoid.6.1.gemfile
- lib/chewy/type/observe.rb
- spec/chewy/strategy/shoryuken_spec.rb
This is a follow up on #623. I'm cherry-picking the same commit on the branch we use in our app. I'm going to wait for green tests and merge.
> Cherry-pick bypass improvement to less-index-updates branch

- .circleci/config.yml
- gemfiles/rails.5.1.mongoid.6.3.gemfile
- gemfiles/rails.6.0.activerecord.gemfile
- lib/chewy/query/nodes/field.rb
- spec/chewy/search/response_spec.rb
- spec/spec_helper.rb
Test locally with:
```
$ circleci local execute --job rspec-ruby-25-activerecord
```
- green build
- Ruby 2.7 support
- ES 7 support
> Setup CI on CircleCI

- .circleci/config.yml
Required before merging https://github.com/toptal/chewy/pull/715
> Added Ruby 2.7 to CircleCI config

- migration_guide.md
https://github.com/toptal/chewy/blob/add-migration-guide/migration_guide.md
> Add migration guide (5.x -> 6.x) draft

- lib/chewy/index.rb
- spec/chewy/index_spec.rb
- spec/chewy/journal_spec.rb
- spec/chewy/minitest/search_index_receiver_spec.rb
- spec/chewy/rake_helper_spec.rb
- spec/chewy/rspec/update_index_spec.rb
- spec/chewy/runtime_spec.rb
- spec/chewy/search/parameters/indices_spec.rb
- spec/chewy/search/request_spec.rb
- spec/chewy/search/response_spec.rb
- spec/chewy/search/scrolling_spec.rb
- spec/chewy/search_spec.rb
- spec/chewy/stash_spec.rb
- spec/chewy/type/import/bulk_builder_spec.rb
- spec/chewy/type/import/journal_builder_spec.rb
- spec/chewy/type/mapping_spec.rb
- spec/chewy_spec.rb
Remove support for the multiple types in mappings.
> Remove multiple types mappings support

- .circleci/config.yml
- CHANGELOG.md
- README.md
- lib/chewy/search/request.rb
- lib/chewy/stash.rb
- lib/chewy/version.rb
- migration_guide.md
- spec/chewy/runtime_spec.rb
- spec/chewy/search/request_spec.rb
- spec/chewy/search/scrolling_spec.rb
Add Elasticsearch 7 support, prepare 7.0.0 release
* (n/a) Commit message starts with `[Fix #issue-number]` (if the related issue exists).
> Add Elasticsearch 7 support, prepare 7.0.0 release

- lib/chewy/search/parameters/concerns/query_storage.rb
- lib/chewy/type/import.rb
> Fix a few typos

- .rubocop.yml
- CHANGELOG.md
- Gemfile
- lib/chewy/index/actions.rb
- lib/chewy/rake_helper.rb
- lib/tasks/chewy.rake
- spec/chewy/index/actions_spec.rb
- spec/chewy/rake_helper_spec.rb
Wrapped Elasticsearch gem .reindex with .reindex in Index class.
Add rake task.
> [Fix #594] Reindex implementation

- CHANGELOG.md
- Gemfile
- lib/chewy/index/actions.rb
- lib/chewy/rake_helper.rb
- lib/tasks/chewy.rake
- spec/chewy/index/actions_spec.rb
- spec/chewy/rake_helper_spec.rb
Wrapped Elasticsearch .put_mapping with .update_mapping in Index class.
> [Fix #692] Update index mapping

- CHANGELOG.md
- README.md
- lib/chewy/version.rb
- migration_guide.md
Prepare 7.2.0 release
* (n/a) Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* (n/a) Added tests.
> Prepare 7.2.0 release

- CHANGELOG.md
- README.md
Update `progressbar` description in Readme and CHANGELOG.
> Update progressbar description in Readme and CHANGELOG

- CHANGELOG.md
- migration_guide.md
Update CHANGELOG & Migration Guide to reflect [7.0.1 release](https://github.com/toptal/chewy/pull/792).
* (n/a) Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* (n/a) Added tests.
> Update CHANGELOG & Migration Guide to reflect 7.0.1 release

- CHANGELOG.md
- lib/chewy/search/parameters/track_total_hits.rb
- lib/chewy/search/request.rb
- spec/chewy/search/parameters/track_total_hits_spec.rb
- spec/chewy/search/request_spec.rb
Return the accurate total hits.
More here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#track-total-hits
> Add the `track_total_hits` option to the query

- README.md
Fixes wrong parentheses in the README file.
> Fix parentheses in Readme

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.2.5 release

- .github/workflows/ruby.yml
> Enable CI checks for PRs

- README.md
Enriching the section on index manipulation with an example of calling an import bang method.
I have adjusted the section on index manipulations to simplify the search and make the section more coherent and complete.
> Enrich README with import! doc

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.2.6 release

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.2.7 release

- README.md
Just caught a couple of minor typos in the README
> fixed a few typos in the Readme file

- .github/CODEOWNERS
> Change Chewy team owner name

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.3.0 release

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.3.1 release

- CHANGELOG.md
- lib/chewy/version.rb
> Prepare 7.3.2 release

- CHANGELOG.md
- lib/chewy/version.rb
> Bump version to 7.3.4

- .github/dependabot.yml
[DEVX-2907]
See PR title
Specs
[DEVX-2907]: https://toptal-core.atlassian.net/browse/DEVX-2907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add dependabot configuation

- CHANGELOG.md
- lib/chewy/version.rb
> Bump version to 7.3.5

- CHANGELOG.md
- lib/chewy/version.rb
> Bump version and update changelog

- CHANGELOG.md
- lib/chewy/version.rb
> Make a release 7.4.0

- CHANGELOG.md
- README.md
- lib/chewy.rb
- lib/chewy/config.rb
- lib/chewy/elastic_client.rb
- spec/chewy/elastic_client_spec.rb
- spec/chewy_spec.rb
Any request done to the ES will be intercepted by `before_search_request_filter`.
> Add before request filter

- CHANGELOG.md
- lib/chewy/version.rb
> Bump chewy to 7.5.0

- CHANGELOG.md
- lib/chewy/version.rb
> Bump version to 7.6.0

- .github/workflows/ruby.yml
- gemfiles/rails.7.2.activerecord.gemfile
> Adding Ruby 3.3 and Rails 7.2 to CI matrix
