toptal/chewy

lib/chewy/railtie.rb
lib/tasks/chewy.rake

I'm sure this used to work, but maybe I'm misremembering. If you have a rails app that includes engines and those engines define chewy indexes, they are not found by the rake task when you do ```rake chewy:update:all```. 
What is the reasoning for using this:
```ruby
Rails.application.config.paths['app/chewy'].existent
```
and then globbing further?

eager load should find indexes inside engines too

---

lib/chewy/query.rb
spec/chewy/query_spec.rb

By passing params scripts can now be cached even when we want to pass values to them.
Unfortunately I have a very limited grasp on both ElasticSearch and Chewy so please advise if this is the wrong way to go about it or if this is already implemented somewhere (I couldn't find it).

Allow scrip_score to receive params

---

README.md

UsersIndex.types_hash
NoMethodError: undefined method `types_hash' for UsersIndex

[Fix doc] s/types_hash/type_hash

---

lib/chewy/index.rb

The regex in this particular case is guaranteed to occur maximum once in any input string, so it is safe to use `sub` instead of `gsub` there. Although it probably doesn't matter here, `sub` is also a bit faster than `gsub`.
```ruby
require 'benchmark/ips'
Benchmark.ips do |ips|
ips.report('gsub') { 'UserIndex'.gsub(/Index\Z/, '') }
ips.report( 'sub') { 'UserIndex'. sub(/Index\Z/, '') }
end
__END__
Calculating -------------------------------------
gsub    20.930k i/100ms
sub    39.750k i/100ms
-------------------------------------------------
gsub    333.065k (± 3.6%) i/s -      1.674M
sub    971.413k (±12.5%) i/s -      4.691M
```

Replace `gsub(/blah\Z/, )` with `sub(/blah\Z/, )`

---

spec/chewy/fields/base_spec.rb
spec/chewy/type/adapter/mongoid_spec.rb

I added ordering by `:id` scope to `has_many :cities` association to prevent random test behavior.
It think, it reproduces randomly. This ones failed:
* https://travis-ci.org/toptal/chewy/jobs/55774252
* https://travis-ci.org/toptal/chewy/jobs/55774278
But other ones from https://travis-ci.org/toptal/chewy/builds/55774229 are not.
The reason is:
expected: {:country=>{"id"=>1, "cities"=>[{"id"=>1, "name"=>"City1"}, {"id"=>2, "name"=>"City2"}]}}
got: {:country=>{"id"=>1, "cities"=>[{"id"=>2, "name"=>"City2"}, {"id"=>1, "name"=>"City1"}]}}
It's just improper ordering.
I turned on SQL logging on specs and figured out this:
% rspec spec/chewy/fields/base_spec.rb:333
...
D, [2015-03-25T13:47:07.055722 #21393] DEBUG -- :    (0.0ms)  begin transaction
D, [2015-03-25T13:47:07.058849 #21393] DEBUG …

Fix cities ordering to prevent random test failing

---

README.md
lib/chewy/type/observe.rb
spec/chewy/type/observe_spec.rb

Hello! I'm using "One Language per Document" pattern (https://www.elastic.co/guide/en/elasticsearch/guide/current/one-lang-docs.html) and I need to define types dynamically. My PR will help with this issue.
Example:
```ruby
class BooksIndex < Chewy::Index
%w(ru en).each do |language|
define_type Book.where(language: language), name: "book_#{language}" do
field :title, type: 'string', analyzer: language
end
end
end
class Book < ActiveRecord::Base
update_index(->(book) {"books#book_#{book.language}"}) { self }
end
```

Accept table name for update_index as a Proc

---

lib/chewy/rspec/update_index.rb

Just simple typo in update_index.rb.

Fix typo in update_index.rb

---

lib/chewy.rb
lib/chewy/query.rb

The aim is to reduce monkey patching of core classes which is undesirable, especially when this gem is used outside of Rails app.

Require only core extensions which are actually used

---

lib/chewy/type/adapter/active_record.rb

This solves https://github.com/toptal/chewy/issues/214 (at toptal/chewy)

Fix duplicate ids on index import

---

lib/chewy/type/adapter/active_record.rb

Hi again!
Here in my company we are relying heavily on Chewy right now, and we are looking for performance bottlenecks, since we are using some complex views in the database right now.
Regarding https://github.com/toptal/chewy/issues/214, we saw that still we could make it faster if we somehow could remove all the OUTER JOINS that come up in the query as a result of eager loading with Active Record's include. So I asked around at StackOverflow (http://stackoverflow.com/questions/31436175/in-an-activerecord-relation-with-eager-loading-how-can-you-pluck-the-primary-co#comment-50842906), and someone came up with a way to do just that.
Do you think there might be any unintended side-effect because of that? I'm still waiting for the tests to pass...

fix-duplicate-ids-on-index-import -> now with better performance

---

lib/chewy/type/adapter/active_record.rb
spec/chewy/type/adapter/active_record_spec.rb

Sometimes relations has default_scope with order clause that depends on
related model (usually with :through). `pluck` selects only one column, so
columns in order clause is missing. Reordering with no order does the trick.

Fix pluck_ids method for ActiveRecord adapter

---

lib/chewy/type/adapter/active_record.rb
spec/chewy/type/adapter/active_record_spec.rb

Reverts toptal/chewy#229
It breaks import! With no order batch load fails.

Revert "Fix pluck_ids method for ActiveRecord adapter"

---

lib/chewy/rake_helper.rb

When running the "update all" or "reset all" rake tasks, Chewy would
search all "app/chewy" folders for each Rails engine for indexes to
update or reset. However, if a Rails engine did not have an app/chewy
folder defined, the rake task would fail. This change compacts the
folder list to first remove the list of Rails engines that do not have
the folder defined, before checking to see if there are any existing
indexes in those folders.

In rake tasks, only search Rails engines with defined app/chewy folders

---

lib/chewy/railtie.rb

In this code we don't need position on text, only matching.
Benchmark code: https://gist.github.com/biow0lf/e4cd0082899c2d83f3fe
```
igor@Zubkov-PC:~/opensource/chewy$ ruby benchmark.rb 
user     system      total        real
43.820000   0.020000  43.840000 ( 47.276215)
20.930000   0.020000  20.950000 ( 22.135514)
igor@Zubkov-PC:~/opensource/chewy$ 
```

Make it faster

---

spec/chewy/index/actions_spec.rb
spec/chewy/strategy_spec.rb

This fixes a few rspec-related warnings I've spotted during initial test runs.

Fix rspec-specific warnings

---

README.md

This describes the two different syntaxes for geo_point fields.

Add instructions for geo_point fields to README

---

lib/chewy/strategy/sidekiq.rb

When I set request_strategy to sidekiq I have many object updates. I have many sidekiq jobs for update in queue. It's ok. But if nil return in observe callback like this 
`update_index('users#user') { self if user_have_changes? }` I get many sidekiq jobs with `[]` argument
Maybe it would be better not to perform sidekiq worker when there no ids?

Do not perform sidekiq workers if no ids present

---

lib/chewy/strategy/active_job.rb
spec/chewy/strategy/active_job_spec.rb

Follow up to #266.
Uses the 'chewy' queue for active job jobs. Gets rid of excess active job logging in tests.

Active job queue

---

lib/chewy/railtie.rb

In our app we have configured a different assets prefix since we have an `AssetsController` with corresponding routes. In this controller, the request strategy is not being used, but should be.

use the configured assets prefix instead of hardcoding /assets

---

lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb

Hello!
Unsubscription should be done safely and here is the fix.
This bug is not as inoffensive as it seems at first sight. Block passed to `subscribe` *captures* method `*args` (fat activerecord objects, maybe with references to loaded associations). These captured objects are never garbage collected.
Needless to say that it also overwhelms the callback chain that slows everything down.

Safely unsubscribe Notifications subscriber.

---

lib/chewy/rspec/update_index.rb

There is a bug when we have mocha in Gemfile but not use it as mock framework in rspec.

Check current rspec.mock_framework instead of simple usage of defined?

---

README.md

Without searching through the code, it wasn't very clear that one should use `request_strategy` to modify the controller strategy. Adding it to the README reduces the need to go through the code.

Add note about Chewy.request_strategy in README

---

Gemfile
lib/chewy/errors.rb
lib/chewy/query.rb
lib/chewy/type/import.rb
spec/chewy/fields/time_fields_spec.rb
spec/chewy/index/actions_spec.rb
spec/chewy/query/pagination_spec.rb
spec/chewy/query_spec.rb
spec/chewy/runtime_spec.rb
spec/chewy/type/actions_spec.rb
spec/chewy/type/import_spec.rb
spec/support/class_helpers.rb

Tested on:
1. v1.7.3
2. v2.0
3. v2.1
a) with delete-by-query plugin
b) without delete-by-query plugin
Maybe someone can setup v2.x version on Travis CI.

Add support for elasticsearch v2.0...v2.1

---

lib/chewy.rb
spec/chewy_spec.rb

A use case for it is setting up a connection to AWS Elasticsearch.
According to elasticsearch-transport's readme one should pass a block to ::ElasticsearchClient#initialize which adds necessary authorization headers to each request. However this can't be done with chewy.
A possible hack as it was discussed in the issue #296 is to assign Thread.current[:chewy_client] somewhere (say, in Rails initializer) with a custom instance. But this would affect only the current thread.
With `:proc` option it becomes possible to pass a block to `Elasticsearch::Constructor`.
So an example initializer for AWS tuning looks like this:
```ruby
require 'faraday_middleware/aws_signers_v4'
Chewy.configuration[:transport_options] = {
headers: { content_type: 'application/json' },
proc: -> (f) do
f.request …
```

add proc transport option

---

lib/chewy/railtie.rb

The change in #277 unfortunately breaks Rails applications in API mode (Rails 5 or via the `rails-api` gem): When configuring an application API only, the `Rails.application.config.assets` entry isn't available and the `RequestStrategy` middleware crashes the application. This now checks if the application is running on api-only mode and does the test for the assets-path afterwards.

Guard against assets not being configured

---

lib/chewy/strategy.rb
spec/chewy/strategy_spec.rb

Passing non-exising strategy to Chewy::Strateg#wrap caused unclear error: "Can't pop root strategy". Now, push and wrap give back better error when strategy is missing.

Better error handling in Chewy::Strategy#wrap

---

lib/chewy/query.rb
lib/chewy/type/wrapper.rb
spec/chewy/query_spec.rb
spec/chewy/type/wrapper_spec.rb

It seems unexpected to get highlighted attribute calling its name on `Chewy::Type` object:
```ruby
object = Chewy::Query.new.query(match: {name: 'name'})
.highlight(fields: {name: {}}).first
object.name # => '<em>Name</em>'
```
Getting original attribute is really hard: `object._data['_source']['name']`
Main idea here is to reimplement method_missing for `Chewy::Type` so:
- `object.name` will return raw name attribute value (one stored in index)
- `object.name_highlight` will return highlighted name attribute
- `object.name_highlight` will response only when highlighting was turned on in query.

Do not overwrite attributes with highlights

---

lib/chewy/strategy/active_job.rb
lib/chewy/strategy/resque.rb
lib/chewy/strategy/sidekiq.rb
spec/chewy/strategy/active_job_spec.rb
spec/chewy/strategy/resque_spec.rb
spec/chewy/strategy/sidekiq_spec.rb

This pull allows the Sidekiq, Resque, and ActiveJob strategy workers to be called with an options hash to pass to `#import!`. It makes it easy to completely rebuild an index with a different suffix in the background.

Allow worker strategies to receive import options

---

lib/chewy/type.rb
spec/chewy/type_spec.rb

Earlier implementation returned nil on unknown method calls, which would make debugging much harder.

Type#method_missing calls super

---

README.md

Changed backticks to single-quotes - this _is_ a typo, right? Shelling out here would be... interesting.

README: formatting typo

---

lib/chewy/rake_helper.rb
lib/tasks/chewy.rake

When chewy tasks are invoked multiple times from the same environment - their stats are printed as many times as they were invoked. Easiest way to see it is with `rake chewy:update[model1] chewy:reset[model2]`.
This PR makes subscriptions scoped to the task block only.

Use scoped subscription to ActiveSupport::Notifications

---

README.md

I might be wrong here, but it seems that it is not really necessary because we use Advanced Crutches™ Technology to load category names. Please correct me if I'm missing something.

Remove redundant preloading from the example describing Crutches™ Technology

---

lib/chewy.rb
spec/chewy_spec.rb

This avoids passing invalid config values to Elasticsearch::Client.new by stripping `prefix` and `transport_options[proc]` from the config hash.
Fixes #333

Sanitize Elasticsearch::Client config

---

lib/chewy/type.rb
lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb
spec/chewy/type_spec.rb

As mentioned in https://github.com/toptal/chewy/pull/340 adding per type settings for import options would be a nice idea. It allows to tune batch size for each defined type specifically.
@pyromaniac What do you think about it?

Add type specific settings

---

lib/chewy/type/witchcraft.rb

This log lines caused SyntaxError: /usr/local/rvm/gems/jruby-1.7.22/gems/chewy-0.8.4/lib/chewy/type/witchcraft.rb:25: invalid multibyte char (US-ASCII)

Fixed invalid multibyte char error

---

README.md
lib/chewy/index.rb
lib/chewy/query.rb
spec/chewy/index_spec.rb

**Current behavior:**
undefined method `new' for nil:NilClass /usr/local/lib/ruby/gems/2.3.0/bundler/gems/chewy-27a71cc1ed55/lib/chewy/query.rb:1003:in `block in _results'
**New behavior:**
Raises `UndefinedType` with what Index was missing which Type.
```ruby
UsersIndex.type('user') # => UsersIndex::User
UsersIndex.type('foo') # => raises error UndefinedType("Unknown type in UsersIndex: foo")
```

Add method Index.type(type_name) which raises UndefinedType on unknown type_name

---

lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb

Added a test at `spec/chewy/type/import_spec.rb:73` which fails as following:
```
1) Chewy::Type::Import.import :bulk_size 
Failure/Error: result = client.bulk options.merge(header).merge(body: body)
Elasticsearch::Transport::Transport::Errors::BadRequest:
[400] {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}
```
Looks like to be known issue - need a newline at the end of bulk entry, see
https://discuss.elastic.co/t/elastic-search-bulk-post-testing/24065/4
http://stackoverflow.com/a/22997612
This PR adds missing newline so test passes.

Append newline after each bulk request

---

README.md
lib/chewy/type.rb
lib/chewy/type/adapter/active_record.rb
spec/chewy/type/adapter/active_record_spec.rb
spec/chewy/type_spec.rb

A new `raw_import` option was added. Basically, it allows to avoid unnecessary serialization->deserialization cycles when it matters. Often, a lot of time is spent on creating AR objects, typecasting fields, etc. But eventually, it all gets converted back to strings. So why waste resources on unnecessary conversions. Raw Import is added just for this purpose. On one of our indexes, using this feature shanked index reset time from 7.5 minutes to 4.5 minutes.
The details on how to use this feature can be found [in the updated documentation](https://github.com/toptal/chewy/pull/375/files#diff-04c6e90faac2675aa89e2176d2eec7d8R412).

Add support for raw_import flag

---

lib/chewy/query.rb
lib/chewy/search.rb
spec/chewy/query_spec.rb

Example usage from the docs:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

Add a weight scoring function to the search

---

lib/chewy/query.rb
lib/chewy/query/criteria.rb
lib/chewy/search.rb
spec/chewy/query_spec.rb

It removes offset and sets response limit to the total_count value

Add unlimited method to fetch all records from ES

---

lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb

Elasticsearch 2.2+ returns error when trying to delete an object that must have parent but parent is not sent.
This occurs when object is not present, so existing_object is nil. In this case, it was not populating parent key and then causing error routing_missing_exception on Elasticsearch.
The solution is to skip delete if record does not exists.

Fix routing_missing_exception on delete with parent missing

---

Gemfile
README.md
chewy.gemspec
lib/chewy.rb
lib/chewy/index/actions.rb
lib/chewy/journal.rb
lib/chewy/rake_helper.rb
lib/chewy/type.rb
lib/chewy/type/import.rb
lib/tasks/chewy.rake
spec/chewy/index/actions_spec.rb
spec/chewy/journal_spec.rb
spec/spec_helper.rb

It adds journaling for all actions that were made on records. It is optional and can be set using import options, `default_import_options` and Chewy configuration.

Journaling

---

README.md
lib/chewy/minitest.rb
lib/chewy/minitest/helpers.rb
lib/chewy/minitest/search_index_receiver.rb
spec/chewy/minitest/helpers_spec.rb
spec/chewy/minitest/search_index_receiver_spec.rb

This adds support for index update assertions, and methods to control search index cleaning in a Minitest environment.
Critiques and suggestions welcome. One necessary improvement is better integration with the Chewy ORM interoperability layer. Currently the `SearchIndexReceiver#indexed?` and `#deleted?` methods expect an object to respond to `#id`. I'm happy to continue the work and enhance the integration if it's welcome, but I'd like some feedback before investing more time into it. We are currently using these testing helpers as is and they're functional for our needs.
The ideas and implementation in the `SearchIndexReceiver` mock class is largely ported directly from the `rspec/update_index` implementation of `update_index` and friends. I'm sure it would be possible to make both test …

Minitest assertions and indexing controls.

---

lib/chewy/config.rb
lib/chewy/railtie.rb
lib/chewy/rake_helper.rb
spec/chewy/config_spec.rb

Hello again!
In our rails application directory we have the following folders:
```
assets/
contexts/
controllers/
errors/
exporters/
helpers/
jobs/
mailers/
models/
policies/
serializers/
views/
```
While integrating the Chewy gem, I added the `app/chewy` folder to the application. There were a few complaints that 'chewy' didn't match the convention applied in the `app/` directory, and so I was able to change it to `app/indices` with a little creative monkey patching.
This patch allows the directory to be set with a new config option called `index_definition_path`.
I tried to find every place the path was hard coded and replace with `Chewy.configuration[:index_definition_path]`.
Additionally, the default setting is `app/chewy` so current deployments shouldn't need to change anything. …

Allow app/chewy location to be changed via yml config

---

lib/chewy/search.rb

After that fix readme example should run correctly:
https://github.com/toptal/chewy#script-fields

Missing `script_fields` in the search delegate

---

lib/chewy/config.rb

Currently, running rubocop results in
```
lib/chewy/config.rb:129:34: W: Unnecessary splat expansion.
file = Rails.root.join(*%w(config chewy.yml))
```
- the expansion is needed here, unless one would change the code
- because rubocop does not recognize that this is needed, it should be
ok to disable this cop for this line using an end-of-line comment
@pyromaniac I would like to request to merge this or an equivalent fix soon, so that I can rebase #428 with this. Currently all tests on travis seem to fail only because of this single rubocop warning.

Silence rubocop warning about unnecessay splat expansion

---

lib/chewy/journal.rb

Running the specs with elasticsearch 2.1.2 reveals an error in [spec/chewy/index/actions_spec#413](https://github.com/toptal/chewy/blob/master/spec/chewy/index/actions_spec.rb#L413)
```
rspec ./spec/chewy/index/actions_spec.rb:409 # Chewy::Index::Actions.reset! journaling should not eq 0
```
Digging into this with `pry` reveals the following error while executing `import`
```ruby
{:create=>
{{"type"=>"mapper_parsing_exception",
"reason"=>"failed to parse [created_at]",
"caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"1474461120\" is malformed at \"20\""}}=>
["AVdMuzzyVa0tBwCq2J07"]}}
```
The problem arises because
* the mapping stats, that `created_at` is a date with the format `basic_date_time`
* see …

Make journals work with elasticsearch 2.x

---

lib/chewy/index.rb
lib/chewy/journal.rb
lib/chewy/type.rb
spec/chewy/journal_spec.rb
spec/chewy_spec.rb

Fixes #431. Let me know what you think. Thanks!

Add support for namespaced indexes in journaling

---

lib/chewy/config.rb

Once I run `rake chewy:reset` it raised an error with:
```
TypeError: no implicit conversion of nil into String
```
Once I set `indices_path` in a chewy.yml file then this issue was solved.
Since this change now `indices_path` used by default, so you don't need to set it through chewy.yml.

Use default indices_path path

---

.rubocop_todo.yml
CHANGELOG.md
lib/chewy/query.rb
lib/chewy/search.rb
spec/chewy/query_spec.rb

`_score` to be computed and tracked even when there are no `_score` in sort.
More here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html

Add the `track_scores` option to the query

---

lib/chewy/config.rb

This bug seems to have been introduced by https://github.com/toptal/chewy/pull/433.
The `indices_path` setting from config will always be overwritten by `indices_path` which is `app/chewy`.
`configuration[:indices_path] = indices_path if indices_path`
This prevents `indices_path` setting from config from being overwritten by indices_path if the setting is not nil.

Fixed indices_path config setting

---

lib/chewy/strategy/sidekiq.rb

I added the same name of  `queue` when `Sidekiq` strategy is being invoked. The `ActiveJob` and `Resque` contain default queue named `chewy`, so might be helpful to add to `Sidekiq` as well.

Add chewy as the default Sidekiq queue

---

spec/chewy/config_spec.rb

This is adding a spec for https://github.com/toptal/chewy/pull/436
This test makes sure that the `indices_path` config in settings is not overridden by the default `indices_path`.

Added specs for indices_path setting on configuration

---

.rubocop_todo.yml
CHANGELOG.md
lib/chewy/query.rb
lib/chewy/search.rb
spec/chewy/query_spec.rb

This PR enables the `preference` option on `Query` which allows the user to control the preference for determining which shard replicas are used for a search request.
See: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html

Add preference param to Query

---

lib/chewy/journal.rb
lib/chewy/rake_helper.rb
spec/chewy/journal_spec.rb

When resetting an index that has journaling, the current code actually replays all the journal entries, no matter which index has just been reset.
This PR only applies journal entries for the given index. I find my code a bit clunky (the new `query` method).
Any thoughts?

Only apply journal for current index when resetting

---

README.md
chewy.gemspec
lib/chewy/fields/base.rb
lib/chewy/index.rb
lib/chewy/journal.rb
lib/chewy/journal/apply.rb
lib/chewy/journal/clean.rb
lib/chewy/journal/entry.rb
lib/chewy/journal/query.rb
lib/chewy/rake_helper.rb
lib/chewy/rspec/update_index.rb
lib/chewy/strategy/base.rb
lib/chewy/strategy/bypass.rb
lib/tasks/chewy.rake
spec/chewy/journal/apply_spec.rb
spec/chewy/journal/entry_spec.rb
spec/chewy/journal_spec.rb
spec/chewy/type/witchcraft_spec.rb

Refactor `Chewy::Journal`
Add multiple retries to apply the journal

Ensure journal is empty

---

lib/chewy/strategy/sidekiq.rb
lib/chewy/type/witchcraft.rb
spec/chewy/strategy/sidekiq_spec.rb

This allows users to configure wich sidekiq queue to use,
so that the default job/strategy can be used with existing
setups.

Make sidekiq queue configurable

---

lib/chewy/index.rb
lib/chewy/index/settings.rb
spec/chewy/index/settings_spec.rb

Hi Arkadiy (@pyromaniac), I added test.
about case where it may be use:
if we keep  a synonyms/stopwords in db then in the settings we can use synonyms from db
for instance:
```
class ProductsIndex < Chewy::Index
settings proc {
{
analysis: {
filter: {
synonym: {
type: 'synonym',
ignore_case: true,
synonyms: SearchSynonym.synonyms
},
custom_stop: {
type: 'stop',
stopwords: SearchStopWord.terms
},
.....
```
and we can update settings after changes SearchSynonym.synonyms
```
Chewy.client.indices.put_settings(
index: productsIndex.index_name,
body: {
index: {
analysis: {
filter: {
synonym: {
synonyms: SearchSynonym.synonyms
}
} } } }
)
```

add able to use Proc for settings

---

.rubocop_todo.yml
README.md
lib/chewy.rb
lib/chewy/rake_helper.rb
lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb
spec/chewy_spec.rb

It is configurable by `skip_index_creation_on_import` parameter in
`config/chewy.yml`.

Add ability to skip index existence checks on each import

---

README.md

This PR fixes the documentation of the README YAML configuration to enable journaling.
The previous value would become the String `"true,"`, not the `TrueClass` value.

README: Fix YAML example in journaling manual

---

README.md

Related: 
https://github.com/toptal/chewy/pull/301
https://github.com/toptal/chewy/pull/302

Help aws users find the configuration information they need

---

lib/chewy/search/request.rb
lib/chewy/search/scrolling.rb
spec/chewy/search/request_spec.rb
spec/chewy/search/scrolling_spec.rb

Add instrumentation to search and scroll with `search_query.chewy` name.

Add ActiveSupport instrumentation for new DSL

---

lib/chewy/rake_helper.rb

Before, the class was checked to see if it was an instance
of the base class it inherits from.

Fixes check on class of index.

---

lib/chewy/rake_helper.rb

The previous fix broke string index names.

Repairs class check in rake helper.

---

CHANGELOG.md
lib/chewy/config.rb
lib/chewy/type/mapping.rb
spec/chewy/type/mapping_spec.rb

Allow setting default type root options. It can be useful when we want to disable _all field for all types.

Add default root options setting

---

lib/chewy/config.rb
lib/chewy/fields/base.rb
lib/chewy/stash.rb
spec/chewy/fields/base_spec.rb

Allow to sets default type for any field. By default, it is set to 'string'.

Add default field type setting

---

Appraisals
CHANGELOG.md
Gemfile
README.md
gemfiles/rails.4.0.activerecord.gemfile
gemfiles/rails.4.1.activerecord.gemfile
gemfiles/rails.4.2.activerecord.gemfile
gemfiles/rails.4.2.mongoid.5.1.gemfile
gemfiles/rails.5.0.activerecord.gemfile
gemfiles/rails.5.0.mongoid.6.0.gemfile
gemfiles/rails.5.1.activerecord.gemfile
gemfiles/rails.5.1.mongoid.6.1.gemfile
lib/chewy/strategy.rb
lib/chewy/strategy/shoryuken.rb
spec/chewy/strategy/shoryuken_spec.rb
spec/spec_helper.rb

I added a new strategy for AWS SQS-based queues using the shoryuken gem.

Add shoryuken async strategy

---

README.md

According to the screenshot, _Parallelizing rake tasks_ should be on the same level as previous items.
Having _Parallelizing rake tasks_ section as a subsection of `chewy:deploy` doesn't really make much sense.
Before:
After:

Make _Parallelizing rake tasks_ h4 (was: h5)

---

lib/chewy/railtie.rb
lib/chewy/strategy.rb

Right now all requests are being wrapped with `Chewy.strategy(Chewy.request_strategy) { @app.call(env) }`. So every request will have two log entries for default `Chewy.request_strategy`  added and removed from stack.
Here's what current log looks like:
```
Started GET "/articles" for 127.0.0.1 at 2017-07-22 20:25:44 +0300
DEBUG: Chewy strategies stack: [2] <- atomic @ **/chewy/lib/chewy/railtie.rb:17
Processing by ArticlesController#shared as HTML
ArticlesIndex::Article Search (5.9ms) {:index=>["designs"], ***}
Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::JsonApi (2.3ms)
Completed 200 OK in 12ms (Views: 2.9ms | ActiveRecord: 0.0ms)
DEBUG: Chewy strategies stack: [2] -> atomic @ **/chewy/lib/chewy/railtie.rb:17
```
Since most developers are …

Suppress request strategy log messages for every request

---

lib/chewy/search/pagination/will_paginate.rb
spec/chewy/search/pagination/kaminari_spec.rb
spec/chewy/search/pagination/will_paginate_spec.rb

Initialize will paginate collection array correctly

---

lib/sequel/plugins/chewy_observe.rb

http://sequel.jeremyevans.net/rdoc/files/doc/release_notes/4_45_0_txt.html

Remove deprecation warning for ChewyObserve (sequel 4.45.0+)

---

lib/chewy/type/wrapper.rb
spec/chewy/query_spec.rb

Hello, it is very helpful library! Thank you so much)
It seems you missed check with your own method in wrapper highlight method.
I'm not sure is it good practice or not to use elasticsearch without query or use it with wildcard, but in  this case we need to check that _data  contains key "highlights" and _data['highlights'] contains key which is equal to attribute name. 
Moreover - you already have this method!)

Wrapper: missed check in highlight method

---

lib/chewy/type/adapter/sequel.rb

Sequel throws deprecation warnings when using its older symbol-splitting syntax (`:table__column`).
Additionally, `Model.table_name` in `sequel` can return a non-`String`/`Symbol` value.
Uses `::Sequel.qualify` to join `table_name` and `column`.
Uses the `Sequel::SQL::QualifiedIdentifier` returned from `Chewy::Type::Adapter::Sequel#full_column_name` appropriately in the relevant `scope` filters.
I see there is already a PR for this (#542), but it looks like the build isn't passing.

Fix Sequel deprecation warnings

---

lib/chewy/config.rb

Prior to ruby version 2.2.0 the `include` method was private. Use `send` here to maintain compatibility through older versions.

Add compatibility for ruby < 2.2.0

---

lib/chewy/fields/root.rb

We're porting the current Chewy version to ActiveSupport 3.2. (Official support was dropped, don't really know why - you just need to port pluck and stringify_keys from Rails 4 and that's almost all..).
But, in Rails 4 came option `ActiveRecord::Base.include_root_in_json = true`, with this configuration all `as_json` return root key. (Like it was default in Rails 3).

Always ignore root in as_json to ignore include_root_in_json in AR

---

lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb

Passing `[]` or another equivalent of an empty reflection to `Index.import!` makes two requests to the corresponding Elasticsearch index. `GET /index` and `PUT /index` to ensure whether the index exists, and to update the index.
Given a complicated record which triggers many Chewy index updates on associations, this might result in N+1 requests, which might be undesired.
This change adds avoids these requests whenever the reflection is empty.

Avoid Elasticsearch index updates when passing empty reflections

---

lib/chewy/type/observe.rb

It makes sense to short-circuit Chewy's `update_proc` when current strategy is `bypass`.
Currently, even when current strategy is to bypass ES, Chewy still takes time to evaluate the backreference (which is an AR relation, usually).
It's better to skip it as it affects the performance of an application.
Why not put `next if ...` in the beginning of the proc?
Because `Chewy.derive_type` may cause some chewy types to load, if Rails' `eager_load` is `false`. If we stop calling `Chewy.derive_type`, this can cause undesired behavior and bugs, which actually happened in one of the applications I work on. So, in order to preserve existing behavior, we call `derive_type` _before_ `next if`, and the remaining part after the `next if ...`. The remaining part is the heaviest one performance-wise, …

Improve performance of bypassing

---

lib/chewy/config.rb
spec/chewy/config_spec.rb

`Rails` module can be defined without actual Rails gem.
I work on a Sinatra project, which has [ActionView](https://github.com/rails/rails/tree/master/actionview) in dependencies. `ActionView` itself does not depend on Rails, but it has [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L1) and [rails-dom-testing](https://github.com/rails/rails-dom-testing/blob/master/lib/rails/dom/testing/assertions.rb#L4) gems in dependencies, which both define `Rails` module.
Therefore, check `defined?(Rails)` isn't fully valid, and requires hacking on the client app side to make it work (i.e. defining `Rails.root` method and having `config/chewy.yml` file)

Rails::VERSION is more accurate check for presence of Rails

---

lib/chewy/type.rb

Adding pipeline support to default_import_options for easier pipeline use in Type definition of Chewy Index.

Adding pipeline support to default_import_options

---

CHANGELOG.md
lib/chewy/index.rb

to allow legacy names without modifications
actual problem:
we wanna using`chewy` DSL just for querying the data at first
and our legacy name contains some dash symbols

Do not underscore suggested index name

---

README.md
lib/chewy.rb
lib/chewy/fields/base.rb
lib/chewy/index/actions.rb
lib/chewy/index/specification.rb
lib/chewy/rake_helper.rb
lib/chewy/stash.rb
lib/chewy/type/import/journal_builder.rb
lib/chewy/type/import/routine.rb
spec/chewy/index/specification_spec.rb
spec/chewy/journal_spec.rb
spec/chewy/rake_helper_spec.rb
spec/chewy/stash_spec.rb
spec/chewy/type/import/journal_builder_spec.rb

In order to support ES6 we have to split an index with 2 types onto two singe-types indices.
Also, `string` type is not supported, so we use `keyword` with ES2 fallback.
Also, we want to store an unlimited amount of data in specifications because there are guys facing the limits. String data types are limited to several kb of data or so, object fields are limited to 1000 keys by default on a single level. So binary field is the only way to go.

Split stash onto two indices and make it support ES6

---

lib/chewy/type/wrapper.rb

fix typo variable from getting _id,_index,_type

fix typo var data -> _data

---

lib/chewy/type/import/bulk_request.rb
lib/chewy/type/import/journal_builder.rb

If `bulk_size` is set in an index's import options, two additional steps are taken during an index reset:
* Items to be indexed are serialized to JSON so their size is known
* Items are split into multiple bulk requests if they collectively exceed `bulk_size`
I found two performance issues related to those steps. First, the serializer used by Chewy was much slower than the one used by elasticsearch-ruby. If `bulk_size` isn't set this isn't an issue, since Chewy passes everything to elasticsearch-ruby to be serialized. If `bulk_size` is set, though, Chewy needs to know the size of each item in order to complete step two, so it serializes everything with whatever `.to_json` uses (in my case, ActiveSupport/Module::JSON). This commit fixes this by changing Chewy using whatever serializer …

Drastically speed up imports when bulk_size is specified

---

lib/chewy/search/parameters.rb
lib/chewy/search/parameters/allow_partial_search_results.rb
spec/chewy/search/parameters_spec.rb
spec/chewy/search/request_spec.rb

Per ES docs: search_type, request_cache, and the allow_partial_search_results
should not be in the body. They should be sent as query string parameters. (https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-request-body.html#_parameters_4)
My understanding is that chewy should act like this:
``` 
$ IssuesIndex.request_cache(true).render
$ {:index=>["issues"], :type=>["issue"], :body=>{}, :request_cache=>true}
$ {:index=>["issues"], :type=>["issue"], :body=>{:request_cache=>true}
```
I believe this resolves #586 and part of #642.
This is my first PR to this repo so please let me know if you'd like any changes. The second commit (Adding AllowPartialSearchResults parameter) is definitely optional as it supports an ES 6 feature. What do you think?

Add query string parameter support

---

lib/chewy/railtie.rb

Currently Chewy inserts request_strategy middleware after Rails::Rack::Logger. However people can use their custom loggers or use other gems, for instance https://github.com/rocketjob/rails_semantic_logger
Such gems swap `Rails::Rack::Logger` middleware with their implementations so on a moment when Chewy wants to insert its middleware after `Rails::Rack::Logger` it doesn't exist in the chain. 
In this PR instead of relying on `Rails::Rack::Logger` existence we place Chewy middleware before `ActionDispatch::ShowExceptions` that goes right after loggers. 
This also fixes this https://github.com/toptal/chewy/issues/286

Insert request_strategy middleware before ActionDispatch::ShowExceptions

---

CHANGELOG.md
lib/chewy/version.rb

Turns out that we have breaking changes in release 5.0.1
We need to convert it to 5.1.0 release

Prepare release 5.1.0

---

lib/chewy/backports/duplicable.rb

This fixes the warning:
```
warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

Fix deprecation warning for contructing new BigDecimal

---

README.md
lib/chewy/strategy/active_job.rb
lib/chewy/strategy/sidekiq.rb
spec/chewy/strategy/active_job_spec.rb
spec/chewy/strategy/shoryuken_spec.rb
spec/chewy/strategy/sidekiq_spec.rb

We can configure sidekiq queue in settings, but ActiveJob queue name was hadcoded. This PR changes this and allows configuring AJ queue by setting ` Chewy.settings[:active_job][:queue]`.

Allow configuration of Active Job queue name

---

lib/chewy.rb
lib/chewy/fields/base.rb
lib/chewy/fields/root.rb
lib/chewy/type/mapping.rb
lib/chewy/version.rb
spec/chewy/config_spec.rb
spec/chewy/journal_spec.rb
spec/chewy/type/import/bulk_builder_spec.rb
spec/chewy/type/observe_spec.rb

Addresses https://github.com/toptal/chewy/issues/700
All tests are passing

Fixed all deprecation warnings in Ruby 2.7

---

lib/chewy/query/loading.rb
lib/chewy/search/loader.rb
lib/chewy/type/adapter/active_record.rb
lib/chewy/type/adapter/mongoid.rb
lib/chewy/type/adapter/orm.rb
lib/chewy/type/adapter/sequel.rb
lib/chewy/type/import.rb
lib/chewy/type/import/routine.rb

Fixes deprecation warnings
```
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
1. Fixed warning when calling `response.records`, warning backtrace:
```
```
2. Fixed warning when calling `SomeIndex.reset!((Time.now.to_f * 1000).round)`, warning backtrace:
```
```
3. Same  `SomeIndex.reset!((Time.now.to_f * 1000).round)`, warning backtrace:
```
```

Fix more ruby 2.7 keyword params deprecation warnings

---

README.md

Fix instructions for AWS ElasticSearch configuration in README as it is outdated.

Update instructions for AWS ElasticSearch

---

CHANGELOG.md
lib/chewy/index/actions.rb
lib/chewy/search/request.rb
spec/chewy/index/actions_spec.rb
spec/chewy/type/adapter/active_record_spec.rb

Hi, since some peoples seems to work/wish to make Chewy compatible with ElasticSearch 6-7, here is a small PR to fix the deprecation warning from ElasticSearch. It seems to be a good first step.

Patch ElasticSearch deprecation warning

---

.circleci/config.yml
CHANGELOG.md
Gemfile
README.md
chewy.gemspec
gemfiles/rails.6.1.activerecord.gemfile
gemfiles/ruby3.gemfile
lib/chewy/index/actions.rb
lib/chewy/search/parameters.rb
lib/chewy/type/observe.rb
lib/chewy/version.rb
spec/chewy/fields/base_spec.rb
spec/chewy/search/parameters_spec.rb
spec/chewy/search_spec.rb

Add support for Ruby 3

---

lib/chewy/type/witchcraft.rb
spec/chewy/type/witchcraft_spec.rb

The functionality of Chewy without witchcraft enabled simply nulls out any children fields where the child is null. With witchcraft enabled, Chewy will try to traverse objects even when a child is null. Code change addresses this issue.

Fix nil children when using witchcraft

---

README.md
lib/chewy/config.rb
migration_guide.md

The only usage of `string` that I found in chewy was hidden in `Chewy::Runtime.version < '5.0'`. I've updated comments and started a file with migration guide.

Document string vs keyword/text for ES6

---

README.md
lib/chewy/fields/base.rb
spec/chewy/search_spec.rb
spec/spec_helper.rb

not_analyzed and string types are deprecated in the es5.
Also, I've removed the default value `srting` for old versions of the elastic search.
No new failing specs were introduced.

Remove not analyzed

---

CHANGELOG.md
lib/chewy/index/actions.rb
spec/chewy/index/actions_spec.rb

Just a rebase of #698 with one more spec added to cover empty relations.

Avoid importing everything when given an empty relation

---

CHANGELOG.md
lib/chewy/type.rb
lib/chewy/type/adapter/orm.rb
lib/chewy/type/import.rb
spec/chewy/type/adapter/active_record_spec.rb
spec/support/active_record.rb

Just a rebase of https://github.com/toptal/chewy/pull/637 with added spec and a small fix regarding id types

Add support for direct_import parameter to skip objects reloading

---

lib/chewy/index/actions.rb
lib/chewy/type/syncer.rb

See https://www.elastic.co/guide/en/elasticsearch/reference/6.8/removal-of-types.html & https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0
We still have some deprecation warnings on 6.7.x, but they are gone on 6.8.x

Add `include_type_name` parameter for ES 6.7-6.8

---

CHANGELOG.md
lib/chewy/type/wrapper.rb
spec/chewy/query_spec.rb
spec/chewy/type/wrapper_spec.rb

Just a rebase of https://github.com/toptal/chewy/pull/387
It also, instead of adding breaking change, adds a new method `*_highlights` that implements new behavior.

attribute_highlights returns an array of highlights

---

CHANGELOG.md
lib/chewy/multi_search.rb
lib/chewy/search/request.rb
spec/chewy/multi_search_spec.rb
spec/chewy/search/request_spec.rb

Rebase of https://github.com/toptal/chewy/pull/687

Add Chewy::MultiSearch Feature

---

README.md

Documents more details avoid to doubts like the ones raised at: https://github.com/toptal/chewy/pull/703

Explain briefly the existence of `outdated_sync_field` at README

---

CHANGELOG.md
lib/chewy/type/import.rb
spec/chewy/type/import_spec.rb
spec/support/active_record.rb

Address the issue raised here: https://github.com/toptal/chewy/issues/716
There was some unnecessary, possibly heavy, queries being done.
----------------

[FIX-716] Avoid fetching scope data to check if it is blank

---

CHANGELOG.md
lib/chewy/index/actions.rb
lib/chewy/index/aliases.rb
spec/chewy/index/actions_spec.rb
spec/chewy/index/aliases_spec.rb

Just a rebased version of https://github.com/toptal/chewy/pull/689

Correctly report indices and aliases

---

CHANGELOG.md
lib/chewy/railtie.rb

Ruby 2.0 already have a better alternative to `alias_method_chain` which is `Module#prepend`. (Don't remember exactly when introduced).
There is no reason to continue using `alias_method_chain`, and it was causing some conflicts with other gems.

[Fix #722] Remove alias_method_chain, use Module#prepend instead

---

CHANGELOG.md
README.md

In the main README.md:
- there are no leftovers like deprecated/removed features descriptions;
- add a “Getting Started” section, containing an example with the most basic usage of the gem;
- add information which versions of AR are supported by each major Chewy release;
- explain how Elasticsearch client options is passed to the ￼Elasticseach::Client.new

Review and update documentation

---

CHANGELOG.md
lib/chewy/config.rb
lib/chewy/railtie.rb
spec/chewy/config_spec.rb

Remove default setting of :urgent strategy for console if there is another current strategy.

[Fix #495] Default rails console strategy configuration

---

CHANGELOG.md
README.md
lib/chewy/index/actions.rb
spec/chewy/index/actions_spec.rb

Wrapped Elasticsearch::API::Indices::Actions#clear_cache with .clear_cache in Index class.

[Fix #679] Clear cache

---

README.md

Fixed a typo in readme for chewy index filename user_index.rb which gives an error. The right filename is users_index.rb

fix a typo in readme

---

migration_guide.md

Fixed 'Breaking changes in 7.0' URL in the migration guide, which had an additional `l` in `.html`.

Fixed 'Breaking changes in 7.0' URL in the migration guide

---

CHANGELOG.md
lib/chewy/search/parameters/order.rb
spec/chewy/search/parameters/order_spec.rb
spec/chewy/search/parameters_spec.rb
spec/chewy/search/request_spec.rb

Use Array to store the value of Chewy::Search::Parameters::Order.
To allow multiple sorting options that may have the same key name.
For example script based sorting whose key will always be `_script`.

[Fix #795] Change implementation of Order param

---

lib/chewy.rb
lib/chewy/runtime.rb
lib/chewy/search/scoping.rb
spec/chewy_spec.rb

Currently, it's dangerous to use Chewy with dry-effects, because it runs fibers that reset Thread local state.  This PR isolates thread-local variables access, so it could be easily extended. 
After isolating them, we can provide dry-effects integration. 
See https://github.com/dry-rb/dry-effects/issues/82 for the details. 

Use Chewy.thread_local_data to access Thread.current

---

lib/chewy.rb
lib/chewy/runtime.rb
lib/chewy/search/scoping.rb
spec/chewy_spec.rb

We don't want to specify in the variable's name how the data is stored, to be able to change an underlying implementation easily.
Currently, the name is confusing: it says `thread_local_data`, but it stores values in fiber-local  🤷‍♂️

Rename Chewy.thread_local_data to Chewy.current

---

lib/chewy.rb

Use thread-local variables instead of fiber-local variables to store global configuration.
1. Currently, we’re using fiber-local variables. This is indistinguishable from the pre-ruby-1.9 thread-local variables, unless you use fibers and use chewy in those fibers. But if you do - all fiber-local variables are extinguished inside any fiber, explicitly created by `Fiber.new`.
2. If we switch to thread-local variables - i.e. `thread_variable_get/thread_variable_set` - we’re fixing the issue with variables presence inside explicitly created fibers, but introducing a potential issue of having a mess between fibers of one thread, if one decides to use different clients or different strategies in different fibers.
3. If we continue to use fiber-local variables and add a patch on the dry-effects …

Use thread-local variables instead of fiber-local variables to store global configuration.

---

CHANGELOG.md
lib/chewy/config.rb

Psych 4 changes `load` to `safe_load` which doesn't allow aliases in the yaml file. To allow aliases you need to call `unsafe_load` which is what this PR is changing.
This is making similar assumptions to Rails that a file within your project is safe because it is controlled by the project owner. A recent example of how this was fixed in Rails is [here](https://github.com/rails/rails/pull/42687/files)

Use unsafe_load when loading config to support aliases with psych 4

---

chewy.gemspec

We need to avoid elasticsearch gem versions >= 7.14.0 for now.
We have some specs failure with it: https://github.com/toptal/chewy/runs/3240650016
Probably related to https://github.com/elastic/elasticsearch-ruby/blob/master/CHANGELOG.md#client
Also, there are more changes and client can refuse to talk to a server of certain builds (`The client noticed that the server is not a supported distribution of Elasticsearch`), more info: https://github.com/elastic/elasticsearch-py/issues/1639
* (n/a) Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* (n/a) Added tests.
* (n/a) Added an entry to the changelog if the new code introduces user-observable changes. See [changelog entry …

Fixate elasticsearch gem version < 7.14.0

---

.github/workflows/ruby.yml

[CI-601](https://toptal-core.atlassian.net/browse/CI-601)
Using master as as version of 3rd party GitHub action is a potential security risk.
We are changing from:
`uses: elastic/elastic-github-actions/elasticsearch@master`
to:
`uses: elastic/elastic-github-actions/elasticsearch@<SHA-key>`
What I did is just went to the repository, and got the latest SHA of the master.
3rd party GHA repositories changed within this PR:
- [https://github.com/toptal/chewy](url)
How to test
- Green check on this PR is enough
* ~[ ] Added an entry to the changelog if the new code introduces user-observable changes. See [changelog entry format](https://github.com/toptal/chewy/blob/master/CONTRIBUTING.md#changelog-entry-format) for …

fix: change gha version to SHA

---

CHANGELOG.md
lib/chewy/search/parameters.rb
spec/chewy/search/request_spec.rb

This PR moves the preference parameter from the query body to the url as a query parameter. This is in accord with [elasticsearch 7 specification](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-shard-routing.html#shard-and-node-preference).
Current behavior:
```
PostIndex.preference(:_local).wrappers
#=> Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15},"status":400})
```
New behavior post PR:
```
PostIndex.preference(:_local).wrappers
#=> stuff
```
Before submitting the PR make sure the following are …

Move preference to query params

---

README.md

Fixes a wrong path to `mapping.rb` in the Readme file.

Fix mapping.rb link in Readme

---

CHANGELOG.md
lib/tasks/chewy.rake

The `update_mapping` rake task expected the argument, named `index_name`, however, another argument passed to the  `RakeHelper.update_mapping` method

[Fix #825] Mismatch argument names at update_mapping rake task

---

CHANGELOG.md
README.md
lib/chewy/errors.rb
lib/chewy/fields/base.rb
lib/chewy/fields/root.rb
lib/chewy/index/adapter/active_record.rb
lib/chewy/index/adapter/orm.rb
lib/chewy/index/import.rb
lib/chewy/index/import/bulk_builder.rb
lib/chewy/search/request.rb
spec/chewy/fields/base_spec.rb
spec/chewy/index/adapter/active_record_spec.rb
spec/chewy/index/import/bulk_builder_spec.rb
spec/chewy/index/import/routine_spec.rb
spec/chewy/index/import_spec.rb
spec/support/active_record.rb

ES 7.0 support: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#parent-child-mapping-types
Remove [parent/child mapping](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/mapping-parent-field.html
) with parent param, replace with [join field](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html
).

 Replace parent-child mapping with a join field

---

README.md

A few days ago this PR was merged https://github.com/elastic/elasticsearch-ruby/pull/1624 meaning the link isn't working again. Now it's pointing to the `elasticsearch-dsl-ruby` repository

Fixed elasticsearch-dsl link in README

---

CHANGELOG.md
lib/chewy/search.rb
spec/chewy/search_spec.rb

This PR supports keyword arguments in named scopes.
In the current master version, an `ArgumentError` is raised.
Ruby version is 3.0.2.
```ruby
class UsersIndex < Chewy::Index
def self.by_name(name, options:)
end
end
UsersIndex.limit(10).by_name('Martin', options: 'blah blah blah')
```

Support keyword arguments in named scopes

---

lib/chewy/search.rb
spec/chewy/search_spec.rb

Fixes errors introduced in https://github.com/toptal/chewy/pull/835

Fix keyword arguments handling in names scopes

---

migration_guide.md

`elasticsearch/reference/current` url now references Elasticsearch 8.0, which doesn't include the guide on breaking changes in the 7.0 version.
I've adjusted the URL to point to the correct location in `elasticsearch/reference/7.17`

Fixing broken url for Breaking changes in 7.0 in docs.

---

CHANGELOG.md
lib/chewy/search/parameters/collapse.rb
lib/chewy/search/request.rb
spec/chewy/search/parameters/collapse_spec.rb
spec/chewy/search/request_spec.rb

Add the [`collapse`](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) option to the request.
```ruby
PlacesIndex.collapse(field: :name)
```

Add collapse

---

CHANGELOG.md
lib/chewy/journal.rb
spec/chewy/journal_spec.rb

This PR fixes two bugs: 
* Removes the retries principle, just because `Chewy::Stash::Journal.entries` methods as any es query have a limit of default 10 and in case you have more than 100 they are going to be ignored. Instead, pagination is based on the `total_count` will scan through all entires in the journal.
* Another bug is a result of the assumption that entries in the query are sorted by `created_at`, but in reality, it's not.
As an example imagine the following entries in the journal 
```
1. Entry (id: 1, created_at: '12:01:00')
2. Entry (id: 3, created_at: '12:04:00')
3. Entry (id: 2, created_at: '12:03:00')
4. Entry (id: 4, created_at: '12:05:00')
```
and the current algorithm step by step 
1. fetch 2 items older than `12:00:00`, as a result, entries with ids  1, 3 will be …

Fix incorrect pagination in journaling

---

.github/workflows/ruby.yml

Recently have noticed that we run CI checks twice since triggers are configured incorrectly. 
* (n/a) Added tests.
* (n/a) Added an entry to the changelog if the new code introduces user-observable changes. See [changelog entry format](https://github.com/toptal/chewy/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

Optimize CI execution on PR and Push, to not run them twice

---

CHANGELOG.md
README.md
lib/chewy/journal.rb
lib/chewy/rake_helper.rb
lib/chewy/search/request.rb
lib/chewy/stash.rb
lib/tasks/chewy.rake
spec/chewy/rake_helper_spec.rb
spec/chewy/search/request_spec.rb

For the cases when we need to remove a large journal we could benefit from using the async execution provided by [delete-by-query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-task-api) methods
Usage example 
```
rake chewy:journal:clean -- --wait_for_completion=false --requests_per_second=10 --scroll_size=5000
```

Allow asynchronously cleanup journal

---

CHANGELOG.md
lib/chewy/rake_helper.rb
spec/chewy/rake_helper_spec.rb

The method `subscribed_task_stats` wraps almost all methods in RakeHelper but it has a bug.
For instance, the `upgrade` method in the same module is supposed to return a list of changed indexes in https://github.com/toptal/chewy/blob/7d567542c7685cf44a52050b8d16e61c373cd186/lib/chewy/rake_helper.rb#L65-L85
However, the wrapping method isn't returning to the caller the value of `changed_indexes`. Instead, it returns the result of the method `output.puts` which is `nil`.
I'm simply moving `output.puts` to be called within `ensure` so the output of the method correctly returns the result of:
```rb
ActiveSupport::Notifications.subscribed(Chewy::RakeHelper::JOURNAL_CALLBACK.curry[output], "apply_journal.chewy") do
ActiveSupport::Notifications.subscribed(Chewy::RakeHelper::IMPORT_CALLBACK.curry[ …
```

Fix return value of subscribed_task_stats

---

CHANGELOG.md
lib/tasks/chewy.rake
spec/chewy/rake_helper_spec.rb

This task seems to fails in ruby 3.x because keyword arguments are not expanded.
```
$ bundle exec rails "chewy:journal:clean"
rails aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
Tasks: TOP => chewy:journal:clean
(See full trace by running task with --trace)
```
ruby: 3.0.4
chewy: 7.2.7
I added double splat operator.

Fix `chewy:journal:clean` task for ruby 3.x

---

README.md

The current description of the bypass strategy uses the phrase "simply silences index updates" to describe the bypass strategy. I think this is misleading as doing something silently doesn't mean that a process does not happen but rather that there is no output. If I select a process to happen silently, I would expect a normal behaviour but without anything being logged or output to the console.
I believe that the bypass strategy does more than simply suppress output. Instead it bypasses the index update on model save.

Replace bypass strategy description with one that better describes behaviour

---

CHANGELOG.md
lib/chewy/index/import/routine.rb
lib/chewy/rake_helper.rb
lib/tasks/chewy.rake
spec/chewy/index/import_spec.rb
spec/chewy/rake_helper_spec.rb

Adds option to disable journal creation on import. Since it's executed on each import that might save a lot of bandwidth, for our app it's around 20% of all requests. 

Skip journal creation on import

---

CHANGELOG.md
README.md
lib/chewy/rake_helper.rb
lib/tasks/chewy.rake
spec/chewy/rake_helper_spec.rb

Task that create all missing indexes. To be used on production deployments to make sure that newly defined indexes are exists in ES cluster

Add task to create all indexes

---

.github/workflows/ruby.yml
CHANGELOG.md
gemfiles/rails.7.1.activerecord.gemfile
lib/chewy.rb
lib/chewy/log_subscriber.rb

Fixes https://github.com/toptal/chewy/issues/903
`color` method was changed in Rails 7.1, introducing a `mode_options` hash instead of a position parameter just for bold option.
This PR checks the ActiveSupport version and calls `color` method with the proper parameters.
Also, I've added the configuration for executing the CI for Rails 7.1 version

[Fix #903] Fix deprecation warning in LogSubscriber in Rails 7.1

---

CHANGELOG.md
README.md
lib/chewy/strategy/delayed_sidekiq.rb
lib/chewy/strategy/delayed_sidekiq/scheduler.rb
spec/chewy/strategy/delayed_sidekiq_spec.rb

https://github.com/toptal/chewy/pull/869 added the `delayed_sidekiq` strategy, which by design will only create a sidekiq worker to update an index every N seconds (10 seconds by default).
The implementation details for that involves redis sorted sets: it creates a sorted set for each index that uses the strategy and adds a new member to it everytime we call reindex (with the weight being calculated from the current timestamp, generating a unique number every N seconds).
Since we're writing directly to Redis, if we use this strategy in tests we're subject to state leaking and creating flaky tests. For example:
* test A runs some code that calls `MyClass.import!(1, strategy: :delayed_sidekiq)` and not flush the Sidekiq workers or the redis database
* in less than 10 seconds, test B runs …

Add helper to cleanup delayed sidekiq timechunks

---

CHANGELOG.md
README.md
lib/chewy/config.rb
lib/chewy/errors.rb
lib/chewy/index/adapter/active_record.rb
spec/chewy/index/adapter/active_record_spec.rb

Instead of warning, you can completely ignore cases when the scope include order/offset/limit or you can raise an exception instead.
This change is actually a performance improvment. Avoiding `arel` calls to identify it default scope has order/offset/limit is time consuming and we don't need to verify it every time we boot. 
Additional option of raising an exception might be useful for tests to prevent defining scopes with ordering or pagination.

Make default index scope cleanup behavior configurable

---

CHANGELOG.md
chewy.gemspec
lib/chewy/config.rb
spec/chewy/config_spec.rb

Saw the comment here - https://github.com/toptal/chewy/issues/847#issuecomment-1824503608 - which notes that newer 7.x versions of elasticsearch gem allow either Faraday 1.x or 2.x.
This change might be a good stopgap to include in a Chewy 7.x release while work on ES8 support (in Chewy 8) continues on that PR.

Relax allowed `elasticsearch` dependency version

---

CHANGELOG.md
spec/chewy/strategy/delayed_sidekiq_spec.rb

This example was previously failing when it was run at exactly an "even" 10 second increment time. For example, it would fail at "12:00:10", but pass at "12:00:09" and "12:00:11". This leads to intermittent failures on CI (presumably around ~10% of runs).
Updated to use a helper method in the spec which more closely mirrors the scheduler code.
I noticed this during the CI runs from the previous PR ... and was able to verify this pattern by setting a specific time target for the `Timecop.freeze` line, which confirmed the pattern of fail/pass.

Fix intermittent time-based failure in delayed sidekiq spec

---

.github/workflows/ruby.yml
CHANGELOG.md
README.md
gemfiles/base.gemfile
lib/chewy/strategy/delayed_sidekiq.rb
lib/chewy/strategy/delayed_sidekiq/scheduler.rb
lib/chewy/strategy/delayed_sidekiq/worker.rb
spec/chewy/strategy/delayed_sidekiq_spec.rb

1. There is a chance for race conditions exactly in this place.
```ruby
unless redis.zrank(timechunks_key, timechunk_key) # read
redis.zadd(timechunks_key, at, timechunk_key) # write
```             
I eliminated it using Lua script and making the combination of operations atomic.
2. Also, there was a possibility to bloat Redis if there is an issue with reindexing (ES connection timeout for instance)

[fix] delayed_sidekiq race condition

---

CHANGELOG.md
lib/chewy/strategy/delayed_sidekiq/worker.rb
spec/chewy/strategy/delayed_sidekiq_spec.rb
spec/support/active_record.rb

Ensure ids extracted from Redis remain strings, preventing UUID issues. Previously, ids were being converted to integers, causing problems with UUIDs in the `delayed_sidekiq` strategy.
This update also enhances the test suite:
- Existing tests are updated.
- A new test ensures the issue is resolved.
Due to SQLite's lack of UUID support, a `stub_uuid_model` method is added. This method stubs models with UUIDs, using `SecureRandom.uuid` for the primary key.

Fix id conversion issue in delayed_sidekiq strategy
